trigger:
- main
 
variables:
  # El nombre que definiste en el Paso 2.4
  azureServiceConnection: 'conexion-azure-distrocuyo'
  # El nombre exacto de la App en el portal
  webAppName: 'appguarderia-distrocuyo'
  pythonVersion: '3.11'
 
stages:
- stage: Build
  displayName: 'Fase de Compilación'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest' # Usamos el agente de Microsoft para el build de Linux
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)
 
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Instalar dependencias y validar'
 
    - task: ArchiveFiles@2
      displayName: 'Empaquetar código'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
 
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
 
- stage: Deploy
  displayName: 'Fase de Despliegue'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: 'webAppLinux'
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'PYTHON|$(pythonVersion)'
              startUpCommand: 'sh startup.sh'