services:
  guarderia-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guarderia-facturas-container
    ports:
      - "8083:8000"  # <─── Accederás por el puerto 8083 desde tu Windows
    volumes:
      - /opt/guarderia/facturas:/capitalhumano  # <─── PERSISTENCIA: Real en Ubuntu -> Interno en Docker
    environment:
      - FLASK_ENV=production
      # Dejamos declaradas las variables de Entra ID y Azure que el dev use en su .env
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
    restart: unless-stopped